INSERT INTO PLOT (AREA, PLOT_NAME, IRRIGATION_TIME, AMOUNT) VALUES (2, '2 SQUARE ACRES', '1970-01-01 12:00:00', 12);
INSERT INTO SENSOR (PLOT_ID) (SELECT PLOT.ID PLOT_ID FROM PLOT WHERE PLOT_NAME = '2 SQUARE ACRES');
INSERT INTO SENSOR (PLOT_ID) (SELECT PLOT.ID PLOT_ID FROM PLOT WHERE PLOT_NAME = '2 SQUARE ACRES');
INSERT INTO SENSOR (PLOT_ID) (SELECT PLOT.ID PLOT_ID FROM PLOT WHERE PLOT_NAME = '2 SQUARE ACRES');
INSERT INTO SENSOR (PLOT_ID) (SELECT PLOT.ID PLOT_ID FROM PLOT WHERE PLOT_NAME = '2 SQUARE ACRES');
INSERT INTO SENSOR (PLOT_ID) (SELECT PLOT.ID PLOT_ID FROM PLOT WHERE PLOT_NAME = '2 SQUARE ACRES');
INSERT INTO SENSOR (PLOT_ID) (SELECT PLOT.ID PLOT_ID FROM PLOT WHERE PLOT_NAME = '2 SQUARE ACRES');

INSERT INTO PLOT (AREA, PLOT_NAME, IRRIGATION_TIME, AMOUNT) VALUES (3, '3 SQUARE ACRES', '1970-01-01 13:00:00', 18);
INSERT INTO SENSOR (PLOT_ID) (SELECT PLOT.ID PLOT_ID FROM PLOT WHERE PLOT_NAME = '3 SQUARE ACRES');
INSERT INTO SENSOR (PLOT_ID) (SELECT PLOT.ID PLOT_ID FROM PLOT WHERE PLOT_NAME = '3 SQUARE ACRES');
INSERT INTO SENSOR (PLOT_ID) (SELECT PLOT.ID PLOT_ID FROM PLOT WHERE PLOT_NAME = '3 SQUARE ACRES');

INSERT INTO PLOT (AREA, PLOT_NAME, IRRIGATION_TIME, AMOUNT) VALUES (5, '5 SQUARE ACRES', '1970-01-01 14:00:00', 30);
INSERT INTO SENSOR (PLOT_ID) (SELECT PLOT.ID PLOT_ID FROM PLOT WHERE PLOT_NAME = '5 SQUARE ACRES');
INSERT INTO SENSOR (PLOT_ID) (SELECT PLOT.ID PLOT_ID FROM PLOT WHERE PLOT_NAME = '5 SQUARE ACRES');

INSERT INTO PLOT (AREA, PLOT_NAME, IRRIGATION_TIME, AMOUNT) VALUES (7, '7 SQUARE ACRES', '1970-01-01 15:00:00', 42);
INSERT INTO SENSOR (PLOT_ID) (SELECT PLOT.ID PLOT_ID FROM PLOT WHERE PLOT_NAME = '7 SQUARE ACRES');