CREATE TABLE PLOT (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    AREA NUMERIC(12,2) NOT NULL,
    PLOT_NAME VARCHAR(64) NOT NULL,
    IRRIGATION_TIME DATETIME NOT NULL,
    AMOUNT NUMERIC(12, 2) NOT NULL,
    CONSTRAINT PLOT_UQ1 UNIQUE(PLOT_NAME)
);

CREATE TABLE SENSOR (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PLOT_ID BIGINT NOT NULL,
    CONSTRAINT SENSOR_FK1 FOREIGN KEY (PLOT_ID) REFERENCES PLOT(ID)
);

CREATE TABLE JOB_STATUS (
    ID VARCHAR(64) NOT NULL,
    SENSOR_ID BIGINT NOT NULL,
    START_TIME DATETIME NOT NULL,
    END_TIME DATETIME,
    TRIALS INT NOT NULL,
    JOB_STATUS_CODE VARCHAR(64) NOT NULL,
    CONSTRAINT JOB_PK PRIMARY KEY (ID),
    CONSTRAINT JOB_PK_1 FOREIGN KEY (SENSOR_ID) REFERENCES SENSOR(ID)
)